name: Deploy to AWS Amplify

on:
  push:
    branches:
      - master # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
      
      - name: Install backend dependencies
        working-directory: backend/
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy with AWS CDK
        working-directory: backend/
        run: |
          npm run cdk deploy -- --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2


    
